# Generated by Django 4.2.3 on 2023-08-14 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('sub_genero', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('genero', models.CharField(max_length=64)),
                ('sub_genero', models.CharField(max_length=64)),
                ('autor', models.CharField(max_length=256)),
                ('resumen', models.TextField()),
                ('anio', models.IntegerField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
