# Generated by Django 4.2.3 on 2023-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(),
        ),
    ]
