# Generated by Django 4.2.3 on 2023-08-15 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_libreria', '0004_alter_libro_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='creador',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generos',
            name='creador',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
